services:
  - type: web
    name: face-attendance
    env: python
    buildCommand: |
      # Настройка swap-файла
      fallocate -l 8G /swapfile \
        && chmod 600 /swapfile \
        && mkswap /swapfile \
        && swapon /swapfile \
        # Этап 1: Установка системных зависимостей
        && apt-get update && apt-get install -y \
        # Базовые инструменты разработки
        python3-dev \
        build-essential \
        cmake \
        # Математические библиотеки
        libopenblas-dev \
        liblapack-dev \
        libatlas-base-dev \
        # Графические библиотеки
        libx11-dev \
        libgtk-3-dev \
        libjasper-dev \
        libqtgui4 \
        libqt4-test \
        libsm6 \
        libxext6 \
        libxrender-dev \
        # Библиотеки для face-recognition
        libboost-all-dev \
        libdlib-dev \
        python3-dlib \
        # Очистка кэша apt
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        # Этап 2: Установка базовых Python пакетов
        && pip install --no-cache-dir wheel setuptools \
        && pip install --no-cache-dir numpy==1.24.3 \
        # Этап 3: Установка основных зависимостей
        && pip install --no-cache-dir Flask==2.0.1 gunicorn==20.1.0 SQLAlchemy==2.0.23 \
        # Этап 4: Установка пакетов для обработки изображений
        && pip install --no-cache-dir opencv-python-headless==4.8.1.78 Pillow==10.2.0 \
        # Этап 5: Установка face-recognition и остальных пакетов
        && pip install --no-cache-dir face-recognition==1.3.0 \
        && pip install --no-cache-dir python-dotenv==1.0.0 python-dateutil==2.8.2 \
        # Очистка swap-файла
        && swapoff /swapfile \
        && rm /swapfile
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: DLIB_USE_CUDA
        value: "0"
      - key: MAKEFLAGS
        value: "-j1"
      - key: CFLAGS
        value: "-O2 -march=native -mtune=native -pipe"
      - key: CXXFLAGS
        value: "-O2 -march=native -mtune=native -pipe"
      - key: LDFLAGS
        value: "-Wl,--as-needed"
      - key: SWAP_SIZE
        value: "8G" 