services:
  - type: web
    name: face-attendance
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        cmake \
        libopenblas-dev \
        liblapack-dev \
        libx11-dev \
        libgtk-3-dev \
        python3-dev \
        python3-pip \
        libdlib-dev \
        && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: PIP_NO_CACHE_DIR
        value: "1" 